#!/usr/bin/env bash
# =============================================================================
# setup_env.sh — First-time interactive setup for any machine / VM
#
# Creates .env and credentials/gcs-sa-key.json by prompting for values.
# Run once — files persist on disk. Never run again unless secrets rotate.
#
# Usage:
#   chmod +x scripts/setup_env.sh
#   ./scripts/setup_env.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_DIR}/.env"
CREDS_DIR="${REPO_DIR}/credentials"
KEY_FILE="${CREDS_DIR}/gcs-sa-key.json"

# Colour helpers
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[setup]${NC} $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }

echo ""
echo "========================================"
echo "  TaskFlow AI Agent — First-time setup"
echo "========================================"
echo ""

# Guard: skip if already set up
if [[ -f "${ENV_FILE}" && -f "${KEY_FILE}" ]]; then
  warn ".env and gcs-sa-key.json already exist."
  read -rp "Re-run setup and overwrite them? [y/N]: " OVERWRITE
  [[ "${OVERWRITE,,}" == "y" ]] || { echo "Skipped."; exit 0; }
fi

# ---------- helper: prompt with a default ------------------------------------
ask() {
  local prompt="$1" default="${2:-}" var
  if [[ -n "${default}" ]]; then
    read -rp "${prompt} [${default}]: " var
    echo "${var:-${default}}"
  else
    read -rp "${prompt}: " var
    echo "${var}"
  fi
}

ask_secret() {
  local prompt="$1" var
  read -rsp "${prompt}: " var; echo ""
  echo "${var}"
}

echo "--- Anthropic ---"
ANTHROPIC_API_KEY=$(ask_secret "ANTHROPIC_API_KEY")

echo ""
echo "--- Jira ---"
JIRA_BASE_URL=$(ask     "JIRA_BASE_URL"     "https://prodapt-deah.atlassian.net")
JIRA_EMAIL=$(ask        "JIRA_EMAIL"        "")
JIRA_API_TOKEN=$(ask_secret "JIRA_API_TOKEN")
JIRA_PROJECT_KEY=$(ask  "JIRA_PROJECT_KEY"  "SCRUM")

echo ""
echo "--- Database ---"
echo "  Leave blank to use SQLite (default for local dev)."
DB_URL=$(ask "DATABASE_URL" "sqlite:///./taskflow.db")

echo ""
echo "--- GCS ---"
GCS_BUCKET=$(ask       "GCS_BUCKET_NAME"   "deah")
GCS_PROJECT=$(ask      "GCS_PROJECT_ID"    "verizon-data")
GCS_PREFIX=$(ask       "GCS_PREFIX"        "requirements-pod")

# ---------- write .env -------------------------------------------------------
info "Writing ${ENV_FILE} ..."
mkdir -p "${REPO_DIR}"
cat > "${ENV_FILE}" <<EOF
# Generated by setup_env.sh — do not commit
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
LLM_PROVIDER=claude

DATABASE_URL=${DB_URL}
STORAGE_PROVIDER=gcs
GCS_BUCKET_NAME=${GCS_BUCKET}
GCS_PROJECT_ID=${GCS_PROJECT}
GCS_PREFIX=${GCS_PREFIX}
GCS_CREDENTIALS_PATH=./core/requirements_pod/credentials/gcs-sa-key.json

JIRA_BASE_URL=${JIRA_BASE_URL}
JIRA_EMAIL=${JIRA_EMAIL}
JIRA_API_TOKEN=${JIRA_API_TOKEN}
JIRA_PROJECT_KEY=${JIRA_PROJECT_KEY}
EOF
chmod 600 "${ENV_FILE}"
info "  Done."

# ---------- write gcs-sa-key.json --------------------------------------------
echo ""
echo "--- GCS Service Account Key ---"
echo "Paste the full contents of your gcs-sa-key.json below."
echo "When done, press Enter then Ctrl-D on a new line:"
echo ""

mkdir -p "${CREDS_DIR}"
cat > "${KEY_FILE}"        # reads until Ctrl-D
chmod 600 "${KEY_FILE}"

# Validate it looks like JSON
if ! python3 -c "import json,sys; json.load(open('${KEY_FILE}'))" 2>/dev/null; then
  warn "The pasted content doesn't look like valid JSON. Check ${KEY_FILE}."
else
  info "  gcs-sa-key.json written and validated."
fi

# ---------- done -------------------------------------------------------------
echo ""
info "Setup complete. Start the stack with:"
echo ""
echo "  cd ${REPO_DIR}"
echo "  docker compose up --build -d"
echo ""
